config/routes.rb
Hytir::Application.routes.draw do
  match "logout" => "sessions#destroy", :as => "logout"
  match "login" => "sessions#new", :as => "login"
  resources :users
  resources :sessions
  resources :ttns
  resources :drivers
  resources :organizations
  resources :lists
  resources :transports
  resources :cars
  resources :goods

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'sessions#new'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :number, :driver_id, :ttn_ids

  has_many :ttns
  belongs_to :driver
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def create
    @list = List.new(params[:list])
    if @list.save
      redirect_to lists_path
    else
      flash.now[:error] = I18n.t('list_create_error')
      render action: :new
    end
  end

  def edit
    @list = List.find(params[:id])
    render action: :new
  end

  def new
    @list = List.new
  end

  def update
    @list = List.find(params[:id])
    @list.update_attributes(params[:list])
    redirect_to lists_path
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/index.html.slim
.row-fluid
  .span2
    = link_to t('.new_list'), new_list_path, class: 'btn btn-primary btn-large'
.row-fluid
  .span12
    '
.row-fluid
  .span12
    table.table-striped.table-hover.table-bordered
      thead
        th= t('.id')
        th= t('.number')
        th= t('.driver')
        th
        th
      tbody
        - @lists.each do |list|
          tr
            td= list.id
            td= list.number
            td
              - if list.driver
                = list.driver.name
            td= link_to edit_list_path(list) do
              i.icon-pencil
            td= link_to list, confirm: t('.are_you_sure'), method: :delete do
              i.icon-remove

app/views/lists/new.html.slim
= simple_form_for @list, html: {class: 'form-horizontal'} do |f|
  = f.input :number
  = f.input :driver_id, collection: Driver.all, include_blank: false
  = f.button :submit