config/routes.rb
Hytir::Application.routes.draw do
  match "logout" => "sessions#destroy", :as => "logout"
  match "login" => "sessions#new", :as => "login"
  resources :users
  resources :sessions
  resources :ttns
  resources :drivers
  resources :organizations
  resources :lists
  resources :transports
  resources :cars
  resources :goods

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'sessions#new'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/transport.rb
class Transport < ActiveRecord::Base
  attr_accessible :name

  has_many :ttns

  validates :name, uniqueness: true
end

app/controllers/transports_controller.rb
class TransportsController < ApplicationController
  def index
    @transports = Transport.all
  end

  def create
    @transport = Transport.new(params[:transport])
    if @transport.save
      redirect_to transports_path
    else
      flash.now[:error] = I18n.t('.transport_create_error')
      render action: :new
    end
  end

  def edit
    @transport = Transport.find(params[:id])
    render action: :new
  end

  def new
    @transport = Transport.new
  end

  def update
    @transport = Transport.find(params[:id])
    @transport.update_attributes(params[:transport])
    redirect_to transports_path
  end

  def destroy
    @transport = Transport.find(params[:id])
    @transport.destroy
    redirect_to transports_path
  end
end

app/helpers/transports_helper.rb
module TransportsHelper
end

app/views/transports/index.html.slim
.row-fluid
  .span2
    = link_to t('.new_transport'), new_transport_path, class: 'btn btn-primary btn-large'
.row-fluid
  .span12
    '
.row-fluid
  .span12
    table.table-striped.table-hover.table-bordered
      thead
        th= t('.id')
        th= t('.name')
        th
        th
      tbody
        - @transports.each do |transport|
          tr
            td= transport.id
            td= transport.name
            td= link_to edit_transport_path(transport) do
              i.icon-pencil
            td= link_to transport, confirm: t('.are_you_sure'), method: :delete do
              i.icon-remove

app/views/transports/new.html.slim
= simple_form_for @transport, html: {class: 'form-horizontal'} do |f|
  = f.input :name
  = f.button :submit