config/routes.rb
Hytir::Application.routes.draw do
  match "logout" => "sessions#destroy", :as => "logout"
  match "login" => "sessions#new", :as => "login"
  resources :users
  resources :sessions
  resources :ttns
  resources :drivers
  resources :organizations
  resources :lists
  resources :transports
  resources :cars
  resources :goods

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'sessions#new'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/good.rb
class Good < ActiveRecord::Base

  attr_accessible :name

  has_many :ttns

  validates :name, uniqueness: true
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  def index
    @goods = Good.all
  end

  def create
    @good = Good.new(params[:good])
    if @good.save
      redirect_to goods_path
    else
      flash.now[:error] = I18n.t('good_create_error')
      render action: :new
    end
  end

  def edit
    @good = Good.find(params[:id])
    render action: :new
  end

  def new
    @good = Good.new
  end

  def update
    @good = Good.find(params[:id])
    @good.update_attributes(params[:good])
    redirect_to goods_path
  end

  def destroy
    @good = Good.find(params[:id])
    @good.destroy
    redirect_to goods_path
  end
end

app/views/goods/index.html.slim
.row-fluid
  .span2
    = link_to t('.new_good'), new_good_path, class: 'btn btn-primary btn-large'
.row-fluid
  .span12
    '
.row-fluid
  .span12
    table.table-striped.table-hover.table-bordered
      thead
        th= t('.id')
        th= t('.name')
        th
        th
      tbody
        - @goods.each do |good|
          tr
            td= good.id
            td= good.name
            td= link_to edit_good_path(good) do
              i.icon-pencil
            td= link_to good_path(good), :method => 'delete' do
              i.icon-remove

app/views/goods/new.html.slim
= simple_form_for @good, html: {class: 'form-horizontal'} do |f|
  = f.input :name
  = f.button :submit