config/routes.rb
Hytir::Application.routes.draw do
  match "logout" => "sessions#destroy", :as => "logout"
  match "login" => "sessions#new", :as => "login"
  resources :users
  resources :sessions
  resources :ttns
  resources :drivers
  resources :organizations
  resources :lists
  resources :transports
  resources :cars
  resources :goods

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'sessions#new'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  attr_accessible :name

  has_many :ttns
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  def index
    @organizations = Organization.all
  end

  def create
    @organization = Organization.new(params[:organization])
    if @organization.save
      redirect_to organizations_path
    else
      flash.now[:error] = I18n.t('organization_create_error')
      render action: :new
    end
  end

  def edit
    @organization = Organization.find(params[:id])
    render action: :new
  end

  def new
    @organization = Organization.new
  end

  def update
    @organization = Organization.find(params[:id])
    @organization.update_attributes(params[:organization])
    redirect_to organizations_path
  end

  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy
    redirect_to organizations_path
  end

end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/index.html.slim
.row-fluid
  .span2
    = link_to t('.new_organization'), new_organization_path, class: 'btn btn-primary btn-large'
.row-fluid
  .span12
    '
.row-fluid
  .span12
    table.table-striped.table-hover.table-bordered
      thead
        th= t('.id')
        th= t('.name')
        th
        th
      tbody
        - @organizations.each do |org|
          tr
            td= org.id
            td= org.name
            td= link_to edit_organization_path(org) do
              i.icon-pencil
            td= link_to org, method: :delete do
              i.icon-remove

app/views/organizations/new.html.slim
= simple_form_for @organization, html: {class: 'form-horizontal'} do |f|
  = f.input :name
  = f.button :submit